#!/bin/bash
#need to reset 2 times so kernels 5.15 onwards have bluetooth working after resuming from sleep on my machine
#sudo systemctl restart bluetooth.service
#sleep 2s;
bus=$(lsusb | grep 0bda:8771 | cut -b5-7)
dev=$(lsusb | grep 0bda:8771 | cut -b16-18) 
/sbin/usbreset /dev/bus/usb/$bus/$dev;
sleep 8s;
if dmesg | tail | grep hci0 | grep timeout
/sbin/usbreset /dev/bus/usb/$bus/$dev;
else
exit
fi
